name: pharmaconnect_project
description: "A new Flutter project."
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3

  pdf: ^3.3.0

  image_picker: ^0.8.4+8

  sqflite: ^2.0.0+4

  path: ^1.8.0

  printing: ^5.6.2

  path_provider: ^2.0.9

  shared_preferences: ^2.0.6

  video_player: ^2.2.19

  chewie: ^1.2.2

  flutter_localizations:
    sdk: flutter

  youtube_player_flutter: ^8.0.0

  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

   
  flutter_lints: ^3.0.0

 
flutter:
  assets:
    - assets/images/
  uses-material-design: true
 
